blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = "blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("blog/", include("blog.urls", namespace="blog")),
    path("__reload__/", include("django_browser_reload.urls")),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, 'blog_list.html', context)
    
class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            'form': form
        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method=='POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')

        context = {
            
        }
        return render(request, 'blog_create.html', context)
    
class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post': post
        }
        return render(request, 'blog_detail.html', context)
    
class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = "blog_update.html"

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk': pk})
    
class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blog_delete.html"
    success_url = reverse_lazy('blog:home')

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

templates/base.html
{% load static tailwind_tags %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body>

    {% block content %}
    
    {% endblock content %}
    
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Post</h2>

<br />
<form class="w-full max-w-lg" method="POST">
  {% csrf_token %} 
  <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
    Title
  </label>{{form.title}}
  <br />
  <br />
  <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
    Content
  </label>{{form.content}}
  <br />
  <br />
  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" type="submit">
    Submit
  </button>
</form>
{% endblock content %}

templates/blog_delete.html
<h2>Delete Post</h2>
<h2>Are you shore?</h2>

<br />
<form method="POST">
  {% csrf_token %} 
  {{form}}
  <button type="submit">Delete</button>
</form>

templates/blog_detail.html
{% extends 'base.html' %} 

{% block content %}
<div
  class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
>
  <h2
    class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
  >
    Blog Details
  </h2>
  <h3 class="mb-3 text-xl font-bold text-gray-700 dark:text-gray-400">
    {{post.title}}
  </h3>
  <br />
  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
    {{post.content}}
  </p>
  <br />
  <a
    href="{% url 'blog:update' post.id %}"
    class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
  >
    Update
    <svg
      aria-hidden="true"
      class="w-4 h-4 ml-2 -mr-1"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fill-rule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        clip-rule="evenodd"
      ></path>
    </svg>
  </a>
  <a
    href="{% url 'blog:delete' post.id %}"
    class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
  >
    Delete ❌
  </a>
  <a
    href="{% url 'blog:home' %}"
    class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
  >
    Home
    <svg
      aria-hidden="true"
      class="w-4 h-4 ml-2 -mr-1"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fill-rule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        clip-rule="evenodd"
      ></path>
    </svg>
  </a>
</div>
{% endblock content %}

templates/blog_list.html
{% extends 'base.html' %} 

{% block content %}
<div
  class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
>
  <h1
    class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
  >
    Blog List
  </h1>

  {% for post in posts %}
  <a
    class="mb-3 font-bold text-xl text-gray-700 dark:text-gray-400"
    href="{% url 'blog:detail' post.id %}"
  >
    {{post.title}}
  </a>
  <br />
  <br />
  <a
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
    href="{% url 'blog:update' post.id %}"
  >
    Update
  </a>
  <a
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
    href="{% url 'blog:delete' post.id %}"
  >
    Delete
  </a>
  {% endfor %}
  <br />
</div>
<br />
<a
  class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
  href="{% url 'blog:create' %}"
>
  Create Post
</a>
{% endblock content %}

templates/blog_update.html
<h2>Update Post</h2>
<br />
<form method="POST">
  {% csrf_token %} 
  title{{form.title}}
  <br />
  content{{form.content}}
  <br />
  <button type="submit">Submit</button>
</form>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>
        Hola, visita mi blog
        <a class="text-blue-500" href="{% url 'blog:home' %}">aqui👉🏽</a>
    </h2>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>